---
driver_config:
    require_chef_omnibus: 11.12.2

provisioner:
  name: chef_zero
  data_bags_path: "../../data_bags"
  environments_path: "../../environments"
  roles_path: "../../roles"
  nodes_path: "../../nodes"

platforms:
  - name: local
    driver_plugin: vagrant
    driver_config:
      box: amuse-bouche-centos65
      box_url: "http://files.be.lan/installers/vagrant_boxes/amuse-bouche-centos65.box"

  - name: ubuntu-local
    driver_config:
      box: ubuntu_12_04
      box_url: http://download.virtualbox.org/virtualbox/4.3.10/virtualbox-4.3_4.3.10-93012~Ubuntu~precise_i386.deb
