---
driver_config:
    require_chef_omnibus: 11.12.2

provisioner:
  name: chef_zero
  data_bags_path: "../../data_bags"
  environments_path: "../../environments"
  roles_path: "../../roles"
  nodes_path: "../../nodes"

platforms:
  - name: ubuntu-local
    driver_plugin: vagrant
    driver_config:
      box: ubuntu-12-04-desktop
      box_url: "/Users/malcolm/dev/basebox-packer/virtualbox/ubuntu1204-desktop-provisionerless.box"

driver:
  name: vagrant
  customize:
    memory: 2048
